"""个人回收站表增加上级信息

Revision ID: 004c4aa2b3f3
Revises: d6d6ae6d9680
Create Date: 2025-05-21 21:29:14.873544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004c4aa2b3f3'
down_revision: Union[str, None] = 'd6d6ae6d9680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_ibfk_1', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notes_ibfk_1', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.add_column('self_recycle_bin', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('self_recycle_bin', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'self_recycle_bin', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'self_recycle_bin', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'self_recycle_bin', type_='foreignkey')
    op.drop_constraint(None, 'self_recycle_bin', type_='foreignkey')
    op.drop_column('self_recycle_bin', 'folder_id')
    op.drop_column('self_recycle_bin', 'article_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_ibfk_1', 'notes', 'articles', ['article_id'], ['id'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_ibfk_1', 'articles', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###
