"""Article、ArticleDB表增加点击量

Revision ID: 023952869ee6
Revises: f89d896e9b57
Create Date: 2025-05-27 20:53:36.631307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023952869ee6'
down_revision: Union[str, None] = 'f89d896e9b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articleDB', sa.Column('clicks', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'clicks')
    op.drop_column('articleDB', 'clicks')
    # ### end Alembic commands ###
