"""group增加name字段, 改变article的name字段定义

Revision ID: 0c8a143b1c4d
Revises: f0cfac833b7d
Create Date: 2025-04-22 23:25:31.324190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c8a143b1c4d'
down_revision: Union[str, None] = 'f0cfac833b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('groups', sa.Column('name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'name')
    op.alter_column('articles', 'name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
