"""增加文献库简介

Revision ID: 0ff7f968ec3b
Revises: 9256d579f585
Create Date: 2025-06-01 19:36:53.514027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff7f968ec3b'
down_revision: Union[str, None] = '9256d579f585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articleDB', sa.Column('intro', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articleDB', 'intro')
    # ### end Alembic commands ###
