"""增加用户信息

Revision ID: 48b09347ef95
Revises: dfc2d1f9dad2
Create Date: 2025-04-23 16:53:15.415162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = '48b09347ef95'
down_revision: Union[str, None] = 'dfc2d1f9dad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', sa.DateTime(), server_default=func.now(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('university', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('introduction', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_time')
    op.drop_column('users', 'introduction')
    op.drop_column('users', 'university')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
