"""Article表增加所属个人或组织

Revision ID: 56dcd6190dd0
Revises: 023952869ee6
Create Date: 2025-05-27 21:37:05.492437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56dcd6190dd0'
down_revision: Union[str, None] = '023952869ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'group_id')
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
