"""Note表group_id

Revision ID: 6a0b40746e6c
Revises: 618f8bcbc41e
Create Date: 2025-05-27 23:56:45.363419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0b40746e6c'
down_revision: Union[str, None] = '618f8bcbc41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'group_id')
    # ### end Alembic commands ###
