"""增加文献库新

Revision ID: 923af5d7462a
Revises: d7e135e9e071
Create Date: 2025-04-22 12:02:19.315637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923af5d7462a'
down_revision: Union[str, None] = 'd7e135e9e071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articleDB', sa.Column('author', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articleDB', 'author')
    # ### end Alembic commands ###
