"""组织管理数据库

Revision ID: 9256d579f585
Revises: 6a0b40746e6c
Create Date: 2025-05-28 23:35:01.332825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9256d579f585'
down_revision: Union[str, None] = '6a0b40746e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_ibfk_2', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notes_ibfk_4', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_ibfk_4', 'notes', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_ibfk_2', 'articles', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
