"""增加用户信息描述

Revision ID: 949e5fc5dfc4
Revises: a434b17f5caf
Create Date: 2025-05-11 22:31:11.511674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949e5fc5dfc4'
down_revision: Union[str, None] = 'a434b17f5caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'creator_id')
    # ### end Alembic commands ###
