"""文献和文件夹的回收站支持

Revision ID: cf83488540d9
Revises: 
Create Date: 2025-04-20 21:08:32.574488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf83488540d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('visible', sa.Boolean(), nullable=False))
    op.add_column('folders', sa.Column('visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'visible')
    op.drop_column('articles', 'visible')
    # ### end Alembic commands ###
