"""优化user_group和group表

Revision ID: fd8714315ad3
Revises: 004c4aa2b3f3
Create Date: 2025-05-23 13:09:52.425623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd8714315ad3'
down_revision: Union[str, None] = '004c4aa2b3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enter_application')
    op.add_column('groups', sa.Column('avatar', sa.String(length=100), nullable=True))
    op.add_column('user_group', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('user_group', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_group', 'level')
    op.drop_column('groups', 'avatar')
    op.create_table('enter_application',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='enter_application_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='enter_application_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
